-- ===========================================================================
-- ETAPA 4 - Estrutura de dados na nuvem (Supabase / PostgreSQL)
-- ===========================================================================
--
-- COMO APLICAR:
--   1. Abra o projeto em https://supabase.com
--   2. Menu lateral -> SQL Editor -> New query
--   3. Cole este arquivo inteiro e clique em Run
--
-- Rodar duas vezes nao causa problema: tudo aqui usa IF NOT EXISTS ou
-- CREATE OR REPLACE.
-- ---------------------------------------------------------------------------


-- ---------------------------------------------------------------------------
-- Tabela de eventos
-- ---------------------------------------------------------------------------
-- Mesma estrutura da tabela do SQLite local, com tres colunas a mais que so
-- fazem sentido na nuvem (id_local, gravado_em) ou que o Postgres oferece de
-- graca (tipos de verdade: boolean e timestamptz em vez de INTEGER e TEXT).

create table if not exists public.eventos (
    -- Chave primaria da nuvem. Independente do id do SQLite: cada banco
    -- numera as suas linhas.
    id                bigint generated by default as identity primary key,

    -- Qual ESP32 gerou o evento. Permite mais de um dispositivo no mesmo
    -- projeto sem misturar os dados.
    dispositivo       text        not null,

    -- alerta_postura | postura_corrigida | status
    tipo              text        not null,

    -- Quais sensores SW-520D estavam acionados no momento do evento.
    inclinado_frente  boolean     not null default false,
    inclinado_lateral boolean     not null default false,

    -- Quanto tempo a postura ficou inadequada, em segundos.
    duracao_s         integer     not null default 0,

    -- Contadores da sessao, enviados pelo firmware.
    total_alertas     integer     not null default 0,
    uptime_s          integer     not null default 0,

    -- Momento em que o gateway Python recebeu o evento do ESP32.
    recebido_em       timestamptz not null,

    -- Momento em que a nuvem gravou a linha. A diferenca entre as duas
    -- colunas e a latencia do salto para a nuvem -- serve como evidencia
    -- de que o dado realmente saiu da rede local.
    gravado_em        timestamptz not null default now(),

    -- id da mesma linha no SQLite do gateway. Junto com o dispositivo,
    -- identifica o evento de forma unica.
    id_local          integer     not null,

    -- E isto que torna o reenvio seguro. Quando a internet cai, o gateway
    -- guarda os eventos e tenta de novo depois; se uma resposta se perder no
    -- caminho, a tentativa repetida atualiza a linha em vez de duplicar.
    constraint eventos_origem_unica unique (dispositivo, id_local),

    -- Barra dado corrompido antes de entrar no banco.
    constraint eventos_tipo_valido
        check (tipo in ('alerta_postura', 'postura_corrigida', 'status')),
    constraint eventos_duracao_positiva check (duracao_s >= 0)
);

comment on table public.eventos is
    'Eventos de postura enviados pelo ESP32 via gateway Python (projeto de extensao IoT).';


-- ---------------------------------------------------------------------------
-- Indices
-- ---------------------------------------------------------------------------
-- O dashboard sempre pergunta a mesma coisa: "os mais recentes" e "os alertas
-- das ultimas 24h". Os dois indices abaixo atendem exatamente essas consultas.

create index if not exists eventos_recebido_em_idx
    on public.eventos (recebido_em desc);

create index if not exists eventos_tipo_recebido_idx
    on public.eventos (tipo, recebido_em desc);


-- ---------------------------------------------------------------------------
-- View de estatisticas
-- ---------------------------------------------------------------------------
-- A agregacao roda dentro do Postgres, na nuvem. O PC so recebe o resultado
-- pronto: dois numeros, em vez de todas as linhas do dia.

create or replace view public.estatisticas_24h
with (security_invoker = on) as
select
    count(*)::int                    as alertas_24h,
    coalesce(sum(duracao_s), 0)::int as segundos_24h
from public.eventos
where tipo = 'alerta_postura'
  and recebido_em >= now() - interval '24 hours';

comment on view public.estatisticas_24h is
    'Alertas e tempo total de postura inadequada nas ultimas 24 horas.';


-- ---------------------------------------------------------------------------
-- Seguranca (Row Level Security)
-- ---------------------------------------------------------------------------
-- Com RLS ligado e nenhuma policy criada, a chave publica (anon) nao le nem
-- escreve nada: quem abrir a URL do projeto no navegador recebe lista vazia.
-- A chave service_role, usada apenas pelo servidor Python, ignora RLS por
-- definicao e continua funcionando.
--
-- Por isso o dashboard nao fala direto com o Supabase: ele consulta o app.py,
-- que e quem guarda a chave. Nenhuma credencial vai para o navegador.

alter table public.eventos enable row level security;


-- ---------------------------------------------------------------------------
-- Conferencia
-- ---------------------------------------------------------------------------
-- Rode para ver a estrutura criada:
--
--   select column_name, data_type, is_nullable, column_default
--   from information_schema.columns
--   where table_schema = 'public' and table_name = 'eventos'
--   order by ordinal_position;
--
-- E para ver os dados chegando do ESP32:
--
--   select id, dispositivo, tipo, inclinado_frente, inclinado_lateral,
--          duracao_s, recebido_em, gravado_em
--   from public.eventos
--   order by id desc
--   limit 20;
